name: build Docker Image
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag astyle
    - name: ls docker image
      run: docker image ls
    - name: Run
      run: ./run.sh
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/
